### ISSUE TITLE
\TYPO3\CMS\Dbal\Service\SqlSchemaMigrationService should extend \TYPO3\CMS\Install\Service\SqlSchemaMigrationService

### ISSUE THREAD

**Issue by IchHabRecht** [FriendsOfTYPO3/dbal#3]
Installing dbal during the upgrade from TYPO3 7 LTS to TYPO3 8 LTS prevents additional extensions to be downloaded.

By reading the code from EXT:dbal currently this version prevents any extension installation.

Reason:
EXT:dbal registers an xclass for \TYPO3\CMS\Install\Service\SqlSchemaMigrationService. This class (\TYPO3\CMS\Dbal\Service\SqlSchemaMigrationService) is used to be inject in \TYPO3\CMS\Extensionmanager\Utility\InstallUtility::injectInstallToolSqlParser. This method has an own type hint for \TYPO3\CMS\Install\Service\SqlSchemaMigrationService. Injecting an instance of \TYPO3\CMS\Dbal\Service\SqlSchemaMigrationService results in an exception `Argument 1 passed to TYPO3\CMS\Extensionmanager\Utility\InstallUtility::injectInstallToolSqlParser() must be an instance of TYPO3\CMS\Install\Service\SqlSchemaMigrationService, instance of TYPO3\CMS\Dbal\Service\SqlSchemaMigrationService given, called in typo3\sysext\extbase\Classes\Object\Container\Container.php on line 233 `

**Comment by thueske** [comment]
Also got

`
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to TYPO3\CMS\Extensionmanager\Utility\Install
  Utility::injectInstallToolSqlParser() must be an instance of TYPO3\CMS\Inst
  all\Service\SqlSchemaMigrationService, instance of TYPO3\CMS\Dbal\Service\S
  qlSchemaMigrationService given, called in /html/typo3/typo3_src-8.7.3/typo3
  /sysext/extbase/Classes/Object/Container/Container.php on line 233
`

and after applying your patch everything works - thanks! 👍
